services:
  api-solid-pg:
    image: bitnami/postgresql
    container_name: api-solid-pg
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=ignitenode03
    ports:
      - "5432:5432"
